name: dartling_tasks
version: 0.0.2
author: Dzenan Ridjanovic
description: dartling_tasks application that uses dartling for its model with a many-to-many relationship.
homepage: http://ondart.me/
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  browser: any
  dartling:
    git: git://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: git://github.com/dzenanr/dartling_default_app.git
